/**
 * POST /api/social/launch
 * Queues social outreach messages (WhatsApp, LinkedIn, Instagram, Facebook)
 * for all prospects that have the corresponding contact info.
 *
 * Body: { campaign_id, channels: ('whatsapp'|'linkedin'|'instagram'|'facebook')[] }
 *
 * For each prospect × channel, checks:
 *  - Prospect has the contact field (phone, linkedin_url, etc.)
 *  - No existing queued/sent message for that prospect+channel+step
 * Then inserts outreach_messages with status='queued'.
 * Messages are generated and actually sent by the social-send cron.
 */
import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import type { MessageChannel } from '@/types/database'

type SocialChannel = 'whatsapp' | 'linkedin' | 'instagram' | 'facebook'

// Which prospect field maps to which channel
const CHANNEL_FIELD: Record<SocialChannel, string> = {
  whatsapp: 'whatsapp_number',
  linkedin: 'linkedin_url',
  instagram: 'instagram_url',
  facebook: 'facebook_url',
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await request.json()
  const { campaign_id, channels } = body as {
    campaign_id: string
    channels: SocialChannel[]
  }

  if (!campaign_id) return NextResponse.json({ error: 'campaign_id requis' }, { status: 400 })
  if (!channels || channels.length === 0) return NextResponse.json({ error: 'channels requis' }, { status: 400 })

  // Verify campaign ownership
  const { data: campaign } = await supabase
    .from('campaigns')
    .select('id')
    .eq('id', campaign_id)
    .eq('user_id', user.id)
    .single()
  if (!campaign) return NextResponse.json({ error: 'Campaign not found' }, { status: 404 })

  // Load prospects with at least one social contact
  const { data: rawProspects, error: pErr } = await supabase
    .from('prospects')
    .select('id, owner_name, company_name, whatsapp_number, linkedin_url, instagram_url, facebook_url')
    .eq('campaign_id', campaign_id)
    .eq('status', 'to_contact')

  if (pErr) return NextResponse.json({ error: pErr.message }, { status: 500 })
  if (!rawProspects || rawProspects.length === 0) {
    return NextResponse.json({ error: 'Aucun prospect à contacter.' }, { status: 400 })
  }

  const prospects = rawProspects as Array<{
    id: string
    owner_name: string | null
    company_name: string | null
    whatsapp_number: string | null
    linkedin_url: string | null
    instagram_url: string | null
    facebook_url: string | null
  }>

  // Load already queued messages for this campaign (social channels)
  const { data: existing } = await supabase
    .from('outreach_messages')
    .select('prospect_id, channel')
    .eq('campaign_id', campaign_id)
    .eq('sequence_step', 1)
    .in('channel', channels)
    .in('status', ['queued', 'sending', 'sent'])

  // Build set of "prospect_id:channel" already in queue
  const alreadyQueued = new Set(
    (existing ?? []).map(m => `${m.prospect_id}:${m.channel}`)
  )

  const inserts: any[] = []

  for (const prospect of prospects) {
    for (const channel of channels) {
      const field = CHANNEL_FIELD[channel] as keyof typeof prospect
      const contactValue = prospect[field]
      if (!contactValue) continue // no contact info for this channel

      const key = `${prospect.id}:${channel}`
      if (alreadyQueued.has(key)) continue // already queued

      inserts.push({
        prospect_id: prospect.id,
        campaign_id,
        user_id: user.id,
        channel: channel as MessageChannel,
        sequence_step: 1,
        body: '', // generated by cron just before sending
        ai_generated: true,
        status: 'queued',
        scheduled_for: new Date().toISOString(), // immediate
        sent_by_user: false,
      })
    }
  }

  if (inserts.length === 0) {
    return NextResponse.json({
      error: 'Aucun nouveau message à planifier. Soit les prospects n\'ont pas de contacts sociaux, soit ils sont déjà dans la file.',
    }, { status: 400 })
  }

  const { error: insertErr } = await supabase.from('outreach_messages').insert(inserts)
  if (insertErr) return NextResponse.json({ error: insertErr.message }, { status: 500 })

  // Count by channel for response
  const byChannel: Record<string, number> = {}
  for (const m of inserts) {
    byChannel[m.channel] = (byChannel[m.channel] ?? 0) + 1
  }

  return NextResponse.json({ queued: inserts.length, by_channel: byChannel })
}
